### ISSUE TITLE
 Status of ParallelGC

### ISSUE THREAD

**Issue by luneo7** [bell-sw/Liberica#165] opened 2024-03-11 22:44 UTC
I've read that ParallelGC was added to Liberica NIK, but there are no docs about it (settings that you can set), and there was also no update on its state, if it is now production ready or not. So what is the current state of the ParallelGC?

**Comment by voitylov** [comment] 2024-03-12 10:28
closing as duplicate of https://github.com/bell-sw/LibericaNIK/issues/22

**Closed by voitylov** 2024-03-12 10:28 UTC
